[[redirects]]
    from = "/api/*"
    to = "https://top-games-list.fly.dev/api/:splat"
    status = 200
    force = true
    headers = {X-From = "Netlify"}

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200